# Generated by Django 2.2.2 on 2022-11-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mo3_default_spot',
            name='MO5_tagNumber',
        ),
        migrations.AddField(
            model_name='mo3_default_spot',
            name='MO5_tagNumber',
            field=models.ManyToManyField(to='maps.MO5_Tag'),
        ),
        migrations.RemoveField(
            model_name='mo4_original_spot',
            name='MO5_tagNumber',
        ),
        migrations.AddField(
            model_name='mo4_original_spot',
            name='MO5_tagNumber',
            field=models.ManyToManyField(to='maps.MO5_Tag'),
        ),
    ]
