# Generated by Django 2.2.2 on 2023-01-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20221129_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mo3_default_spot',
            name='MO5_tagNumber',
            field=models.ManyToManyField(blank=True, to='maps.MO5_Tag'),
        ),
        migrations.AlterField(
            model_name='mo4_original_spot',
            name='MO4_OspotInfo',
            field=models.TextField(blank=True, null=True, verbose_name='オリジナルスポット情報'),
        ),
        migrations.AlterField(
            model_name='mo4_original_spot',
            name='MO5_tagNumber',
            field=models.ManyToManyField(blank=True, to='maps.MO5_Tag'),
        ),
    ]
