# Generated by Django 2.2.2 on 2023-01-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20230119_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mo4_original_spot',
            name='MO4_OspotAdress',
        ),
        migrations.AddField(
            model_name='mo4_original_spot',
            name='MO4_OspotLat',
            field=models.DecimalField(decimal_places=30, max_digits=32, null=True, verbose_name='オリジナルスポットY座標'),
        ),
        migrations.AddField(
            model_name='mo4_original_spot',
            name='MO4_OspotLng',
            field=models.DecimalField(decimal_places=30, max_digits=32, null=True, verbose_name='オリジナルスポットY座標'),
        ),
    ]
