# Generated by Django 2.2.2 on 2023-01-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_auto_20230124_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mo4_original_spot',
            name='MO4_OspotLat',
            field=models.FloatField(blank=True, null=True, verbose_name='オリジナルスポットY座標'),
        ),
        migrations.AlterField(
            model_name='mo4_original_spot',
            name='MO4_OspotLng',
            field=models.FloatField(blank=True, null=True, verbose_name='オリジナルスポットY座標'),
        ),
    ]
