# Generated by Django 2.2.2 on 2022-11-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MO2_store',
            fields=[
                ('MO2_storeNumber', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='店舗ナンバー')),
                ('MO2_storeName', models.CharField(max_length=30, verbose_name='店舗名')),
                ('MO2_storeInfo', models.TextField(null=True, verbose_name='店舗情報')),
                ('MO2_phoneNumber', models.CharField(max_length=20, null=True, verbose_name='電話番号')),
                ('MO2_address', models.CharField(max_length=50, verbose_name='住所')),
                ('MO2_mailAdress', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('MO2_password', models.CharField(max_length=50, null=True, verbose_name='パスワード')),
                ('MO1_createDate', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('MO1_updateDate', models.DateTimeField(auto_now_add=True, verbose_name='更新日時')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('is_auth', models.BooleanField(default=False, verbose_name='管理者認証')),
            ],
            options={
                'verbose_name_plural': 'MO2_Store',
            },
        ),
    ]
