# Generated by Django 2.2.2 on 2022-11-25 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mo2_store',
            old_name='MO1_createDate',
            new_name='MO2_createDate',
        ),
        migrations.RenameField(
            model_name='mo2_store',
            old_name='MO1_updateDate',
            new_name='MO2_updateDate',
        ),
    ]
