# Generated by Django 2.2.2 on 2022-11-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20221125_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mo2_store',
            name='MO2_password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='パスワード'),
        ),
        migrations.AlterField(
            model_name='mo2_store',
            name='MO2_phoneNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='mo2_store',
            name='MO2_storeInfo',
            field=models.TextField(blank=True, null=True, verbose_name='店舗情報'),
        ),
    ]
