# Generated by Django 2.2.2 on 2022-11-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20221129_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='mo2_store',
            name='last_Login',
            field=models.DateField(null=True, verbose_name='最終ログイン'),
        ),
    ]
