# Generated by Django 2.2.2 on 2022-11-29 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_mo2_store_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mo2_store',
            name='last_Login',
        ),
    ]
