# Generated by Django 2.2.2 on 2023-01-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20230119_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mo2_store',
            name='MO2_images1',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='店舗画像1'),
        ),
        migrations.AlterField(
            model_name='mo2_store',
            name='MO2_images2',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='店舗画像2'),
        ),
        migrations.AlterField(
            model_name='mo2_store',
            name='MO2_images3',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='店舗画像3'),
        ),
    ]
