# Generated by Django 2.2.2 on 2023-01-30 13:14

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20230126_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mo2_store',
            name='MO2_images1',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.member_file_path1, verbose_name='店舗画像1'),
        ),
        migrations.AlterField(
            model_name='mo2_store',
            name='MO2_images2',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.member_file_path2, verbose_name='店舗画像2'),
        ),
        migrations.AlterField(
            model_name='mo2_store',
            name='MO2_images3',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.member_file_path3, verbose_name='店舗画像3'),
        ),
    ]
