# Generated by Django 2.2.2 on 2023-02-06 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20230130_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='MO12_storeEng',
            fields=[
                ('MO12_storeEngNumber', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='英表記ナンバー')),
                ('MO12_storeNameEng', models.CharField(max_length=200, verbose_name='英表記店舗名')),
                ('MO2_storeNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.MO2_store', verbose_name='店舗ナンバー')),
            ],
            options={
                'verbose_name_plural': 'MO12_storeEng',
            },
        ),
    ]
