# Generated by Django 2.2.2 on 2023-02-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_mo12_storeeng'),
    ]

    operations = [
        migrations.AddField(
            model_name='mo12_storeeng',
            name='MO12_storeNameLng',
            field=models.CharField(default='en', max_length=20, verbose_name='選択言語'),
        ),
        migrations.AlterField(
            model_name='mo12_storeeng',
            name='MO12_storeNameEng',
            field=models.CharField(max_length=200, verbose_name='翻訳語店舗名'),
        ),
    ]
