# Generated by Django 2.2.2 on 2023-02-07 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20230206_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mo12_storeeng',
            old_name='MO12_storeNameEng',
            new_name='MO12_storeName',
        ),
    ]
