# Generated by Django 2.2.2 on 2023-02-07 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20230207_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mo12_storeeng',
            old_name='MO12_storeName',
            new_name='MO12_storeNameEnd',
        ),
    ]
