# Generated by Django 2.2.2 on 2023-02-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20230207_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mo2_store',
            name='MO2_storeName',
            field=models.CharField(max_length=50, verbose_name='店舗名'),
        ),
    ]
