# Generated by Django 2.2.2 on 2022-11-28 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221124_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'CustomUser'},
        ),
        migrations.CreateModel(
            name='MO9_Fav_Custom_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MO1_userNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myuser', to=settings.AUTH_USER_MODEL, verbose_name='ユーザナンバー')),
                ('MO9_followedUserNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followeduser', to=settings.AUTH_USER_MODEL, verbose_name='フォローユーザナンバー')),
            ],
            options={
                'verbose_name_plural': 'MO9_Fav_Custom_user',
            },
        ),
        migrations.CreateModel(
            name='MO6_Visit_record',
            fields=[
                ('MO6_visitRecordNumber', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='訪問記録ナンバー')),
                ('MO6_dateofvisit', models.DateTimeField(auto_now_add=True, verbose_name='訪問記録')),
                ('MO1_userNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザナンバー')),
            ],
            options={
                'verbose_name_plural': 'MO6_Visit_record',
            },
        ),
    ]
