# Generated by Django 2.2.2 on 2022-11-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221128_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='MO1_homeCountry',
            field=models.CharField(blank=True, max_length=50, verbose_name='HomeCountry'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='MO1_language',
            field=models.CharField(blank=True, max_length=50, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='MO1_openRange',
            field=models.IntegerField(default=0, verbose_name='OpenRange'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='MO1_userID',
            field=models.CharField(max_length=16, verbose_name='UserID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='MailAddres'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=50, verbose_name='UserName'),
        ),
    ]
