# Generated by Django 2.2.2 on 2022-11-30 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20221129_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mo6_visit_record',
            name='MO3_DspotNumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.MO3_Default_spot', verbose_name='デフォルトスポットナンバー'),
        ),
        migrations.AlterField(
            model_name='mo6_visit_record',
            name='MO4_OspotNumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.MO4_Original_spot', verbose_name='オリジナルスポットナンバー'),
        ),
    ]
