# Generated by Django 2.2.2 on 2022-12-01 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20221130_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='mo6_visit_record',
            name='MO6_createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日時'),
            preserve_default=False,
        ),
    ]
