# Generated by Django 2.2.2 on 2023-01-20 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20230120_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='MO1_userID',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(7)], verbose_name='UserID'),
        ),
    ]
