# Generated by Django 2.2.2 on 2022-11-28 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20221128_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='MO7_Blog',
            fields=[
                ('MO7_blogNumber', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ブログナンバー')),
                ('MO7_blogName', models.CharField(blank=True, max_length=50, verbose_name='ブログ名')),
                ('MO7_blogText', models.TextField(null=True, verbose_name='ブログ内容')),
                ('MO7_openRange', models.IntegerField(default=0, verbose_name='公開範囲')),
                ('MO7_createDate', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('MO7_updateDate', models.DateTimeField(auto_now_add=True, verbose_name='更新日時')),
                ('MO1_userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザID')),
                ('MO6_visitRecordNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.MO6_Visit_record', verbose_name='訪問記録ナンバー')),
            ],
            options={
                'verbose_name_plural': 'MO7_Blog',
            },
        ),
        migrations.CreateModel(
            name='MO10_Fav_Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MO1_userNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザナンバー')),
                ('MO7_blogNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.MO7_Blog', verbose_name='ブログナンバー')),
            ],
            options={
                'verbose_name_plural': 'MO10_Fav_Blog',
            },
        ),
    ]
