# Generated by Django 2.2.2 on 2023-01-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mo7_blog',
            name='MO7_blogName',
            field=models.CharField(max_length=50, verbose_name='ブログ名'),
        ),
    ]
