# Generated by Django 2.2.2 on 2023-01-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230120_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='mo7_blog',
            name='MO7_blogImage1',
            field=models.ImageField(null=True, upload_to='save_path'),
        ),
    ]
