# Generated by Django 2.2.2 on 2023-02-03 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230131_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mo7_blog',
            name='MO7_createDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
    ]
