# Generated by Django 2.2.2 on 2023-01-30 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_auto_20230130_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='MO11_Pointrecord',
            fields=[
                ('MO11_pointRecordNumber', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='ポイント履歴ナンバー')),
                ('MO11_pointSize', models.IntegerField(default=0, verbose_name='使用ポイント')),
                ('MO11_createDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('MO1_userNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザナンバー')),
                ('MO2_storeNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.MO2_store', verbose_name='使用店舗')),
            ],
        ),
    ]
